language: java

jdk: openjdk8

branches:
  only:
    - main

before_install:
  - pip install --user codecov

script:
  - mvn clean test -P travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=eb1a776c-6802-4c65-90cd-6a8a2791e2f4
