language: java

jdk: openjdk8

branches:
  only:
    - main

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - pip install --user codecov

script:
  - mvn clean install -DskipTests=false -P travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=eb1a776c-6802-4c65-90cd-6a8a2791e2f4
