language: java

jdk: openjdk8

branches:
  only:
    - main

before_install:
  - pip install --user codecov

script:
  - mvn clean install -DskipTests=false -P travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=035a54c6-9570-4863-b512-49ed800db266
